Adding better logging (#4)
* Adding better logging and exiting if any nonzero return status

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -21,14 +21,26 @@ for BUILDPACK in $(cat $1/.buildpacks); do
 
     if [[ "$url" =~ \.tgz$ ]] || [[ "$url" =~ \.tgz\? ]]; then
       mkdir -p "$dir"
-      curl -s "$url" | tar xvz -C "$dir" >/dev/null 2>&1
+      curl -s "$url" | tar xvz -C "$dir"
+      if [ $? != 0 ]; then
+        echo "Failed to grab $url"
+        exit 1
+      fi
     else
-      git clone $url $dir >/dev/null 2>&1
+      git clone $url $dir
+      if [ $? != 0 ]; then
+        echo "Failed to clone $url, do you have shopify-dep added as a collaborator to your repo?"
+        exit 1
+      fi
     fi
     cd $dir
 
     if [ "$branch" != "" ]; then
-      git checkout $branch >/dev/null 2>&1
+      git checkout $branch 
+      if [ $? != 0 ]; then
+        echo "Failed to checkout $branch"
+        exit 1
+      fi
     fi
 
     # we'll get errors later if these are needed and don't exist
